# Generated by Django 5.1.3 on 2024-12-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='status',
        ),
    ]
